### ISSUE TITLE
Twice text

### ISSUE THREAD

**Issue by VovaGamesChips** [objection-lol/issues#5] opened 2020-10-17 08:31 UTC
I have another problem, the text is sometim
es repeated twice. It is also repeated in the window on the left.
![Два раза](https://user-images.githubusercontent.com/55021547/96332352-2d73ac80-106c-11eb-91e1-99903ab21793.png)

**Comment by objection-lol** [comment] 2020-10-17 10:27
This could be due to an unstable connection, closing it for now as there's no way to reproduce the problem.

**Closed by objection-lol** 2020-10-17 10:27 UTC
